### ISSUE TITLE
old FSF address in COPYING

### ISSUE THREAD

**Issue by mmckinst** [ThomasDickey/original-mawk#38]
The current `COPYING` that comes with mawk has the old FSF address in it which triggers an error in [rpmlint](https://fedoraproject.org/wiki/Common_Rpmlint_issues#incorrect-fsf-address). 

Can `COPYING` be updated with the latest copy of the GPLv2 at https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt ?

**Comment by ThomasDickey** [comment]
will do that (checked-in last night).  I see a couple of bug-reports which I'll work on before the next upload.

**Comment by ThomasDickey** [comment]
http://invisible-island.net/mawk/CHANGES.html#t20160226
