### ISSUE TITLE
Performance reallocating fields

### ISSUE THREAD

**Issue by kmatt** [ThomasDickey/original-mawk#50]
When looping over fields in mawk 1.3.4 20171017, runtime appears ~5X longer than GNU Awk 4.2.0, unusual for Mawk.

This example shows the issue on CentOS 6.9:

`for (i=5; i<=NF; ++i) { $(i-1) = $i }`

The loop in this example drops field 4 as part of an ETL chain. Is there a better approach?

**Comment by ThomasDickey** [comment]
But it's not simply "looping over fields", but reallocating the numbered parameters.  gawk may have some special optimization for this case, e.g., seeing a simple assignment between the numbered fields.  Or it could be a difference regarding if/how the two update $0 when doing an assignment.

By the way, my CentOS 6.x machine has gawk 3.1.7 (4.2.0 isn't a standard package).

**Comment by kmatt** [comment]
> By the way, my CentOS 6.x machine has gawk 3.1.7 (4.2.0 isn't a standard package).

Correct. I update both gawk and mawk from source releases because even CentOS 7 is only up to gawk 4.0.2 and mawk 20131226

If this is not a performance bug, but simply the result of a different in processing technique, but can be closed as "Works as designed". Entered because its very rare / surprising when mawk does not have a significant performance advantage for my use cases (ETL).

**Comment by ThomasDickey** [comment]
thanks (I'll do some investigation , but may close it as suggested).
