### ISSUE TITLE
type error in arg in call to function

### ISSUE THREAD

**Issue by ghost** [ThomasDickey/original-mawk#52]
~~~sh
$ mawk -W version
mawk 1.3.4 20171017

$ mawk 'function fn(ary) {ary[1]} BEGIN{fn((array))}'
mawk: line 1: type error in arg(1) in call to fn
~~~

Note that Gawk and Nawk work as expected.

http://mail-archive.com/austin-group-l@opengroup.org/msg00884.html

**Comment by svnpenn** [comment]
https://github.com/svnpenn/velour/issues/100

**Comment by jayfoad** [comment]
Looks like the same issue as #33.

**Comment by ThomasDickey** [comment]
agreed (this is a duplicate).

It was also already noted in Austin [#1136](https://www.austingroupbugs.net/view.php?id=1136) about a year before this report.
