### ISSUE TITLE
Deviant "srand" behavior

### ISSUE THREAD

**Issue by ghost** [ThomasDickey/original-mawk#53]
With every commonly used implementation:

- gawk
- gawk --posix
- mawk 1.3.3
- nawk

Running "srand" gives you the unix timestamp:

~~~sh
$ awk 'BEGIN {srand(); print srand()}'
1527387405
~~~

However Mawk 1.3.4 gives something else:

~~~sh
$ mawk 'BEGIN {srand(); printf "%.0f\n", srand()}'
13171862908218520
~~~

**Comment by ThomasDickey** [comment]
It's a configuration option:

https://invisible-island.net/mawk/CHANGES.html#t20140914
<pre>
        + change default for configure option --enable-init-srand to enable
          this (discussion with Mike Brennan).
        + add -W random option to set initial srand() seed.
...
        + modify initialization of srand default seed from time of day to use
          gettimeofday, etc., so that successive runs of mawk are less likely
          to use the same seed value (suggested by Mike Brennan).
</pre>
By the way, there's always a patch-date associated with mawk 1.3.4+

**Comment by svnpenn** [comment]
thats all well and good, but you might want to reconsider.

as `date +%s` is not portable

http://pubs.opengroup.org/onlinepubs/9699919799/utilities/date.html

Awk srand was the only portable was to get unix timestamp

**Comment by svnpenn** [comment]
@ThomasDickey maybe instead consider increasing the precision of unix timesamp,
similar to JavaScript:

~~~js
Date.now()
1527536143355
~~~

this will prevent duplication of seed values, while making it possible to
function with existing workflows.

**Comment by ghost** [comment]
I mostly use PHP now as I grew tired of AWK shortcomings. Closing this.
