### ISSUE TITLE
different versioning scheme

### ISSUE THREAD

**Issue by mmckinst** [ThomasDickey/original-mawk#54]
The versioning scheme mawk uses doesn't always work well with tools used to monitor for new versions of stuff. Specifically the problem is the dash in the version like "1.3.4-20171017". In the version field of an RPM spec file, dashes aren't allowed. 

Could the "1.3.4" be dropped and just do snapshots where the version would be "20171017" ? 

Is doing releases as t20171017 an officially recognized version string (https://github.com/ThomasDickey/mawk-snapshots/releases) ? If so that works perfectly.

**Comment by ThomasDickey** [comment]
Actually the version is the full-length 1.3.4-20171017 (just as done for ncurses 6.1-20180602 for example).   If there's a 1.3.5 (perhaps...) then there'll be a v1_3_5 tag for that, along with the corresponding patch-date t20xxxxxx whatever.  You could just look for the patchdate change (I'm not likely to issue **branch** releases on mawk or anything), but a package should reference the full-length verson.

**Comment by ThomasDickey** [comment]
This has the version-information for instance:

https://github.com/ThomasDickey/mawk-snapshots/blob/master/patchlev.h
