### ISSUE TITLE
FPAT variable not available

### ISSUE THREAD

**Issue by falloutphil** [ThomasDickey/original-mawk#61]
Hi,

More a feature request.  When dealing with CSV files it's usual in AWK to set the FPAT variable to  
`awk -vFPAT='([^,]*)|("[^"]+")'`.

This allows us to deal with CSV where cells contain commas that are not separators.

Any chance of implementing this for mawk?  Or any other way of achieving the same ends?

Thanks!

**Comment by ThomasDickey** [comment]
That's a gawk feature, not present in POSIX or other implementations.

**Comment by ThomasDickey** [comment]
You can see this in the manpage, shortly after this comment:
`Gawk  has  a  too-large  number  of  extensions to POSIX awk.
`
