### ISSUE TITLE
Print line with leading whitespaces -  mawk can't handle (E)RE correctly

### ISSUE THREAD

**Issue by apt4user** [ThomasDickey/original-mawk#67]
Version: mawk 1.3.4 20200120
Hi,
mawk can't handle the following expressions:

`echo " (4 x space)    testtest" | awk '/^[[:space:]]{4}/ {print}'`
=> prints nothing

`echo "  (4 x space)  testtest" | awk '/^[\t]{4}/ {print}'`
=> prints nothing

`echo " (4 x space)   testtest" | awk '/^[ \t]{4}/ {print}'`
=> prints nothing

Greetings

**Comment by ThomasDickey** [comment]
This works for current versions of mawk.
