### ISSUE TITLE
WHINY_USERS handled differently from gawk

### ISSUE THREAD

**Issue by rocimoto** [ThomasDickey/original-mawk#70]
Not sure if this is a real bug but my reading of mawk(1) seems to suggest intended compatibility with gawk.  It appears **WHINY_USERS** must be set _external_ to mawk, i.e. `$ WHINY_USERS=0 mawk ..`,  while the following also works in gawk:

```
 $ gawk 'BEGIN{ENVIRON["WHINY_USERS"]=0;split("12345",a,"");for(i in a)print(i)}'
 $ gawk 'BEGIN{system("set WHINY_USERS=0");split("12345",a,"");for(i in a)print(i)}'
```
Actually gawk doesn't even care if a value is assigned to WHINY_USERS, only that it's set; leaving off "`=0`" works fine.

Testing was conducted within bash and mksh shell sessions on Debian using _mawk 1.3.4 20200120_ and _gawk 5.1.0_ .

**Comment by ThomasDickey** [comment]
gawk hasn't used $WHINY_USERS for a while (and if it did, your second example wouldn't work, since gawk couldn't see the environment variable).

making mawk see the environment variable (for the first example) is something to consider.
