### ISSUE TITLE
implement something like gawk's --posix option

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ThomasDickey/original-mawk#8]
```
Perhaps not using the long options, but a problem with
extensions is feature-creep.

```

Original issue reported on code.google.com by `dic...@his.com` on 28 Jun 2012 at 10:29

**Comment by jarnos** [comment]
At least, mawk 1.3.4 20150503 does not complain about `-Wposix` or `-W posix`.

**Comment by ThomasDickey** [comment]
fixed in [t20240819](https://invisible-island.net/mawk/CHANGES.html#t20240819)
